-- =============================================
-- SBerp v3 - EC2 Oracle DDL
-- 실행 순서: 시퀀스 → 독립 테이블 → 의존 테이블
-- 스키마 접두어 "SBERP". 제거 (sberp 유저로 접속하므로)
-- =============================================

-- =============================================
-- 1. SEQUENCES
-- =============================================
CREATE SEQUENCE APPR_AUDIT_LOG_SEQ       INCREMENT BY 1  START WITH 21    NOCACHE;
CREATE SEQUENCE APPR_AUTO_DELEG_SEQ      INCREMENT BY 50 START WITH 1     CACHE 20;
CREATE SEQUENCE APPR_DOC_SEQ             INCREMENT BY 1  START WITH 3335  NOCACHE;
CREATE SEQUENCE APPR_FILE_SEQ            INCREMENT BY 1  START WITH 1     CACHE 20;
CREATE SEQUENCE APPR_FORM_DELEG_CFG_SEQ  INCREMENT BY 50 START WITH 1     CACHE 20;
CREATE SEQUENCE APPR_FORM_SEQ            INCREMENT BY 1  START WITH 1046  NOCACHE;
CREATE SEQUENCE APPR_LCR_SEQ             INCREMENT BY 1  START WITH 21    CACHE 20;
CREATE SEQUENCE APPR_LINE_FAV_SEQ        INCREMENT BY 1  START WITH 61    CACHE 20;
CREATE SEQUENCE APPR_LINE_SEQ            INCREMENT BY 1  START WITH 2241  NOCACHE;
CREATE SEQUENCE HR_AI_CHAT_LOG_SEQ       INCREMENT BY 1  START WITH 4     NOCACHE;
CREATE SEQUENCE HR_PLCY_CHUNK_SEQ        INCREMENT BY 1  START WITH 23    NOCACHE;
CREATE SEQUENCE HR_PLCY_DOC_SEQ          INCREMENT BY 1  START WITH 2     NOCACHE;
CREATE SEQUENCE LEV_REQ_SEQ              INCREMENT BY 1  START WITH 21    CACHE 20;
CREATE SEQUENCE SAL_ACCT_SEQ             INCREMENT BY 1  START WITH 13    NOCACHE;
CREATE SEQUENCE SAL_AI_CHAT_LOG_SEQ      INCREMENT BY 1  START WITH 4     NOCACHE;
CREATE SEQUENCE SAL_HIST_SEQ             INCREMENT BY 1  START WITH 13    NOCACHE;
CREATE SEQUENCE SAL_INC_TAX_BRKT_SEQ     INCREMENT BY 1  START WITH 11    NOCACHE;
CREATE SEQUENCE SAL_MEAL_ALW_PLCY_SEQ    INCREMENT BY 1  START WITH 4     NOCACHE;
CREATE SEQUENCE SAL_PAY_ITEM_SEQ         INCREMENT BY 1  START WITH 181   NOCACHE;
CREATE SEQUENCE SAL_PAY_SEQ              INCREMENT BY 1  START WITH 19    NOCACHE;
CREATE SEQUENCE SAL_PLCY_CHUNK_SEQ       INCREMENT BY 1  START WITH 14    NOCACHE;
CREATE SEQUENCE SAL_PLCY_DOC_SEQ         INCREMENT BY 1  START WITH 2     NOCACHE;
CREATE SEQUENCE SAL_POS_ALW_SEQ          INCREMENT BY 1  START WITH 6     NOCACHE;
CREATE SEQUENCE SAL_RATE_PLCY_SEQ        INCREMENT BY 1  START WITH 3     NOCACHE;
CREATE SEQUENCE SAL_STD_SEQ              INCREMENT BY 1  START WITH 15    NOCACHE;
CREATE SEQUENCE SEQ_APPLICANT            INCREMENT BY 1  START WITH 35    NOCACHE;
CREATE SEQUENCE SEQ_ATTENDANCE           INCREMENT BY 1  START WITH 525   NOCACHE;
CREATE SEQUENCE SEQ_AUTHORITY            INCREMENT BY 1  START WITH 1011  NOCACHE;
CREATE SEQUENCE SEQ_BIZ_NO_GEN           INCREMENT BY 1  START WITH 16001 NOCACHE;
CREATE SEQUENCE SEQ_COMPANY              INCREMENT BY 1  START WITH 1496  NOCACHE;
CREATE SEQUENCE SEQ_COM_RESOURCE         INCREMENT BY 1  START WITH 1157  NOCACHE;
CREATE SEQUENCE SEQ_DEPARTMENT           INCREMENT BY 1  START WITH 1626  NOCACHE;
CREATE SEQUENCE SEQ_DEPT_TRANSFER_LOG    INCREMENT BY 1  START WITH 1079  NOCACHE;
CREATE SEQUENCE SEQ_EMAIL_LOG            INCREMENT BY 1  START WITH 3     NOCACHE;
CREATE SEQUENCE SEQ_EMPLOYEE             INCREMENT BY 1  START WITH 9899  NOCACHE;
CREATE SEQUENCE SEQ_EMP_AUTH             INCREMENT BY 1  START WITH 1044  NOCACHE;
CREATE SEQUENCE SEQ_EMP_POSITION         INCREMENT BY 1  START WITH 1019  CACHE 20;
CREATE SEQUENCE SEQ_EVAL                 INCREMENT BY 1  START WITH 2020  NOCACHE;
CREATE SEQUENCE SEQ_EVALUATION           INCREMENT BY 1  START WITH 1     CACHE 20;
CREATE SEQUENCE SEQ_EVAL_PERIOD          INCREMENT BY 1  START WITH 1     CACHE 20;
CREATE SEQUENCE SEQ_LEAVE_BALANCE        INCREMENT BY 1  START WITH 1667  NOCACHE;
CREATE SEQUENCE SEQ_LEAVE_GRANT          INCREMENT BY 1  START WITH 1695  NOCACHE;
CREATE SEQUENCE SEQ_LOGIN_HISTORY        INCREMENT BY 1  START WITH 461   CACHE 20;
CREATE SEQUENCE SEQ_NOTICE               INCREMENT BY 1  START WITH 1035  NOCACHE;
CREATE SEQUENCE SEQ_PERIOD               INCREMENT BY 1  START WITH 1012  NOCACHE;
CREATE SEQUENCE SEQ_POSITION             INCREMENT BY 1  START WITH 1226  NOCACHE;
CREATE SEQUENCE SEQ_PROJECT              INCREMENT BY 1  START WITH 1027  NOCACHE;
CREATE SEQUENCE SEQ_PROJECT_MEMBER       INCREMENT BY 1  START WITH 6138  NOCACHE;
CREATE SEQUENCE SEQ_RECRUIT              INCREMENT BY 1  START WITH 23    NOCACHE;
CREATE SEQUENCE SEQ_REPORT               INCREMENT BY 1  START WITH 2017  NOCACHE;
CREATE SEQUENCE SEQ_RESERVATION          INCREMENT BY 1  START WITH 1123  NOCACHE;
CREATE SEQUENCE SEQ_RESUME               INCREMENT BY 1  START WITH 32    NOCACHE;
CREATE SEQUENCE SEQ_RESUME_CHUNK         INCREMENT BY 1  START WITH 76    NOCACHE;
CREATE SEQUENCE SEQ_TASK                 INCREMENT BY 1  START WITH 4115  NOCACHE;

-- =============================================
-- 2. LEVEL 0 - 독립 테이블 (FK 없음)
-- =============================================

CREATE TABLE COMPANY (
    COM_ID           NUMBER NOT NULL,
    INDUSTRY_GRP_CODE VARCHAR2(100) NOT NULL,
    INDUSTRY_CODE    VARCHAR2(100) NOT NULL,
    COM_NAME         VARCHAR2(100) NOT NULL,
    COM_CEO          VARCHAR2(100) NOT NULL,
    BIZ_NO           VARCHAR2(45) NOT NULL,
    COM_TEL          VARCHAR2(100),
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    COM_LOGO         CLOB,
    COM_STATUS       VARCHAR2(20 CHAR),
    CONSTRAINT PK_COMPANY PRIMARY KEY (COM_ID),
    CONSTRAINT UQ_COMPANY_BIZ_NO UNIQUE (BIZ_NO)
);

CREATE TABLE SAL_INC_TAX_BRKT (
    BRKT_ID    NUMBER(19,0) NOT NULL,
    MIN_AMT    NUMBER(15,0) NOT NULL,
    MAX_AMT    NUMBER(15,0),
    TAX_RATE   NUMBER(5,4) NOT NULL,
    EFF_FROM   DATE NOT NULL,
    EFF_TO     DATE,
    CREATED_AT DATE NOT NULL,
    CONSTRAINT PK_SAL_INC_TAX_BRKT PRIMARY KEY (BRKT_ID)
);

CREATE TABLE SAL_RATE_PLCY (
    RATE_ID    NUMBER(19,0) NOT NULL,
    PLCY_YEAR  NUMBER(4,0) NOT NULL,
    PENS_RATE  NUMBER(5,4) NOT NULL,
    HLTH_RATE  NUMBER(5,4) NOT NULL,
    CARE_RATE  NUMBER(5,4) NOT NULL,
    EMPL_RATE  NUMBER(5,4) NOT NULL,
    EFF_FROM   DATE NOT NULL,
    EFF_TO     DATE,
    CREATED_AT DATE NOT NULL,
    CONSTRAINT PK_SAL_RATE_PLCY PRIMARY KEY (RATE_ID)
);

CREATE TABLE LOGIN_HISTORY (
    LOGIN_ID    NUMBER(19,0) NOT NULL,
    EMP_EMAIL   VARCHAR2(100 CHAR) NOT NULL,
    EMP_ID      NUMBER(19,0),
    EMP_NAME    VARCHAR2(50 CHAR),
    FAIL_REASON VARCHAR2(200 CHAR),
    LOGIN_AT    TIMESTAMP(9) NOT NULL,
    LOGIN_IP    VARCHAR2(45 CHAR),
    STATUS      VARCHAR2(1 CHAR) NOT NULL,
    USER_AGENT  VARCHAR2(500 CHAR),
    CONSTRAINT PK_LOGIN_HISTORY PRIMARY KEY (LOGIN_ID)
);

CREATE TABLE HR_PLCY_DOC (
    DOC_ID        NUMBER NOT NULL,
    COM_ID        NUMBER NOT NULL,
    TITLE         VARCHAR2(200) NOT NULL,
    DOC_VERSION   NUMBER NOT NULL,
    ACTV          NUMBER(1,0) DEFAULT 1 NOT NULL,
    SRC_FILE_NAME VARCHAR2(200),
    SRC_FILE_URL  VARCHAR2(500),
    FULL_TEXT      CLOB,
    CREATED_AT    DATE NOT NULL,
    UPDATED_AT    DATE NOT NULL,
    CONSTRAINT CK_HR_PLCY_DOC_ACTV CHECK (ACTV IN (0, 1)),
    CONSTRAINT PK_HR_PLCY_DOC PRIMARY KEY (DOC_ID)
);

CREATE TABLE SAL_PLCY_DOC (
    DOC_ID        NUMBER(19,0) NOT NULL,
    COM_ID        NUMBER(19,0) NOT NULL,
    TITLE         VARCHAR2(200) NOT NULL,
    DOC_VERSION   NUMBER(5,0) DEFAULT 1 NOT NULL,
    ACTV          NUMBER(1,0) DEFAULT 1 NOT NULL,
    SRC_FILE_NAME VARCHAR2(200),
    SRC_FILE_URL  VARCHAR2(500),
    FULL_TEXT      CLOB,
    CREATED_AT    DATE NOT NULL,
    UPDATED_AT    DATE NOT NULL,
    CONSTRAINT CK_SAL_PLCY_DOC_ACTV CHECK (ACTV IN (0, 1)),
    CONSTRAINT PK_SAL_PLCY_DOC PRIMARY KEY (DOC_ID),
    CONSTRAINT FK_SAL_PLCY_DOC_COM FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID)
);

CREATE TABLE SAL_HIST (
    HIST_ID      NUMBER NOT NULL,
    ACTOR_EMP_ID NUMBER NOT NULL,
    ACTOR_NAME   VARCHAR2(100),
    TRGT_EMP_ID  NUMBER,
    COM_ID       NUMBER,
    DOM_TYPE     VARCHAR2(30) NOT NULL,
    TRGT_ID      NUMBER NOT NULL,
    CHG_TYPE     VARCHAR2(20) NOT NULL,
    BFR_VAL      CLOB,
    AFT_VAL      CLOB,
    DESCR        VARCHAR2(2000),
    CREATED_AT   DATE NOT NULL,
    CONSTRAINT CK_SAL_HIST_DOM CHECK (DOM_TYPE IN ('SALARY_STANDARD','SALARY_PAYMENT','SALARY_ACCOUNT')),
    CONSTRAINT CK_SAL_HIST_CHG CHECK (CHG_TYPE IN ('CREATE','UPDATE','DELETE','STATUS_CHANGE','MANUAL_ADJUST')),
    CONSTRAINT PK_SAL_HIST PRIMARY KEY (HIST_ID)
);

-- =============================================
-- 3. LEVEL 1 - COMPANY 의존
-- =============================================

CREATE TABLE EMP_POSITION (
    POS_ID    NUMBER(10,0) NOT NULL,
    POS_CODE  VARCHAR2(20) NOT NULL,
    POS_NAME  VARCHAR2(50 CHAR) NOT NULL,
    POS_ORDER NUMBER(10,0) NOT NULL,
    COM_ID    NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_POS PRIMARY KEY (POS_ID),
    CONSTRAINT UQ_POS_COM_CODE UNIQUE (COM_ID, POS_CODE),
    CONSTRAINT FK_POS_COM FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID)
);

CREATE TABLE AUTHORITY (
    AUT_ID   NUMBER NOT NULL,
    COM_ID   NUMBER NOT NULL,
    AUT_NAME VARCHAR2(50 CHAR),
    CONSTRAINT PK_AUTHORITY PRIMARY KEY (AUT_ID),
    CONSTRAINT UQ_AUTHORITY_COM_NAME UNIQUE (COM_ID, AUT_NAME),
    CONSTRAINT FK_AUTHORITY_COMPANY1 FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID)
);

CREATE TABLE EVALUATION_PERIOD (
    PERIOD_ID     NUMBER NOT NULL,
    COM_ID        NUMBER NOT NULL,
    EVAL_YEAR     NUMBER(4,0) NOT NULL,
    EVAL_TERM     VARCHAR2(10) NOT NULL,
    TITLE         VARCHAR2(200 CHAR) NOT NULL,
    START_DATE    DATE NOT NULL,
    END_DATE      DATE NOT NULL,
    PERIOD_STATUS VARCHAR2(20) DEFAULT 'READY' NOT NULL,
    CREATED_AT    DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT    DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_PERIOD_STATUS CHECK (PERIOD_STATUS IN ('READY','OPEN','CLOSED','REPORTING','REPORTING_FAILED','REPORTED')),
    CONSTRAINT CK_PERIOD_TERM CHECK (EVAL_TERM IN ('H1','H2','ANNUAL')),
    CONSTRAINT CK_PERIOD_DATE CHECK (END_DATE >= START_DATE),
    CONSTRAINT CK_PERIOD_YEAR CHECK (EVAL_YEAR BETWEEN 2000 AND 2100),
    CONSTRAINT PK_PERIOD PRIMARY KEY (PERIOD_ID),
    CONSTRAINT UQ_PERIOD_COM_YEAR_TERM UNIQUE (COM_ID, EVAL_YEAR, EVAL_TERM),
    CONSTRAINT FK_PERIOD_COM FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID)
);

CREATE TABLE SAL_MEAL_ALW_PLCY (
    MEAL_PLCY_ID NUMBER(19,0) NOT NULL,
    COM_ID       NUMBER(19,0),
    AMT          NUMBER(15,0) NOT NULL,
    EFF_FROM     DATE NOT NULL,
    EFF_TO       DATE,
    CREATED_AT   DATE NOT NULL,
    CONSTRAINT PK_SAL_MEAL_ALW_PLCY PRIMARY KEY (MEAL_PLCY_ID),
    CONSTRAINT FK_SAL_MEAL_ALW_PLCY_COM FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID)
);

CREATE TABLE SAL_POS_ALW (
    ALW_ID     NUMBER(19,0) NOT NULL,
    POS        VARCHAR2(30) NOT NULL,
    COM_ID     NUMBER(19,0) NOT NULL,
    AMT        NUMBER(15,0) NOT NULL,
    EFF_FROM   DATE NOT NULL,
    EFF_TO     DATE,
    CREATED_AT DATE NOT NULL,
    CONSTRAINT PK_SAL_POS_ALW PRIMARY KEY (ALW_ID),
    CONSTRAINT FK_SAL_POS_ALW_COM FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID)
);

CREATE TABLE HR_PLCY_CHUNK (
    CHUNK_ID        NUMBER NOT NULL,
    DOC_ID          NUMBER NOT NULL,
    CHUNK_ORDER     NUMBER NOT NULL,
    ARTICLE         VARCHAR2(50),
    PAGE            NUMBER,
    CHUNK_TEXT      CLOB NOT NULL,
    CHUNK_EMBEDDING CLOB NOT NULL,
    CONSTRAINT PK_HR_PLCY_CHUNK PRIMARY KEY (CHUNK_ID),
    CONSTRAINT FK_HR_PLCY_CHUNK_DOC FOREIGN KEY (DOC_ID) REFERENCES HR_PLCY_DOC (DOC_ID)
);

CREATE TABLE SAL_PLCY_CHUNK (
    CHUNK_ID        NUMBER(19,0) NOT NULL,
    DOC_ID          NUMBER(19,0) NOT NULL,
    CHUNK_ORDER     NUMBER(10,0) NOT NULL,
    ARTICLE         VARCHAR2(50),
    PAGE            NUMBER(5,0),
    CHUNK_TEXT      CLOB,
    CHUNK_EMBEDDING CLOB,
    CONSTRAINT PK_SAL_PLCY_CHUNK PRIMARY KEY (CHUNK_ID),
    CONSTRAINT FK_SAL_PLCY_CHUNK_DOC FOREIGN KEY (DOC_ID) REFERENCES SAL_PLCY_DOC (DOC_ID)
);

CREATE TABLE APPR_FORM (
    FOR_ID       NUMBER NOT NULL,
    COM_ID       NUMBER NOT NULL,
    FOR_CODE     VARCHAR2(50) NOT NULL,
    FOR_TITLE    VARCHAR2(50) NOT NULL,
    FOR_CONTENT  CLOB,
    FOR_SCHEMA   CLOB,
    FOR_STATUS   NUMBER(1,0) NOT NULL,
    IS_DELETED   NUMBER(1,0) DEFAULT 0 NOT NULL,
    FOR_VERSION  NUMBER DEFAULT 1 NOT NULL,
    CREATED_AT   DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT   DATE DEFAULT SYSDATE NOT NULL,
    FOR_CATEGORY VARCHAR2(20) DEFAULT '기본값' NOT NULL,
    CONSTRAINT CHK_APPR_FORM_STATUS CHECK (FOR_STATUS IN (0,1)),
    CONSTRAINT CHK_APPR_FORM_DELETE CHECK (IS_DELETED IN (0,1)),
    CONSTRAINT PK_APPR_FORM PRIMARY KEY (FOR_ID, FOR_VERSION),
    CONSTRAINT UQ_APPR_FORM_COM_CODE UNIQUE (COM_ID, FOR_CODE, FOR_VERSION),
    CONSTRAINT FK_APPR_FORM_COMPANY1 FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID)
);

-- =============================================
-- 4. LEVEL 2 - DEPARTMENT (순환 참조: EMPLOYEE FK는 나중에 추가)
-- =============================================

CREATE TABLE DEPARTMENT (
    DEPT_ID     NUMBER NOT NULL,
    COM_ID      NUMBER NOT NULL,
    PARENT_ID   NUMBER,
    DEPT_NAME   VARCHAR2(100),
    DEPT_CODE   VARCHAR2(100),
    DEPTH       NUMBER,
    SORT_ORDER  NUMBER,
    EMP_ID      NUMBER,
    DEPT_STATUS VARCHAR2(100) DEFAULT 'ACTIVE',
    CREATED_AT  DATE DEFAULT SYSDATE,
    UPDATED_AT  DATE DEFAULT SYSDATE,
    IS_DELETED  NUMBER(1,0) DEFAULT 0 NOT NULL,
    CONSTRAINT CK_DEPARTMENT_STATUS CHECK (DEPT_STATUS IN ('ACTIVE','PENDING_DELETE','DELETED')),
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPT_ID),
    CONSTRAINT UQ_DEPARTMENT_COM_CODE UNIQUE (COM_ID, DEPT_CODE),
    CHECK (IS_DELETED IN (0,1)),
    CONSTRAINT FK_DEPARTMENT_COMPANY1 FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID),
    CONSTRAINT FK_DEPARTMENT_DEPARTMENT1 FOREIGN KEY (PARENT_ID) REFERENCES DEPARTMENT (DEPT_ID) ON DELETE CASCADE
    -- FK to EMPLOYEE 는 아래에서 ALTER TABLE로 추가
);

-- =============================================
-- 5. LEVEL 3 - EMPLOYEE
-- =============================================

CREATE TABLE EMPLOYEE (
    EMP_ID          NUMBER(10,0) NOT NULL,
    EMP_NO          VARCHAR2(20) NOT NULL,
    EMP_NAME        VARCHAR2(50) NOT NULL,
    EMP_PASS        VARCHAR2(200 CHAR) NOT NULL,
    EMP_EMAIL       VARCHAR2(100) NOT NULL,
    EMP_MOBILE      VARCHAR2(20) NOT NULL,
    EMP_STATUS      VARCHAR2(10) DEFAULT '재직',
    HIRE_DATE       DATE,
    CREATED_AT      DATE DEFAULT SYSDATE,
    UPDATED_AT      DATE DEFAULT SYSDATE,
    COM_ID          NUMBER(10,0) NOT NULL,
    POS_ID          NUMBER(10,0) NOT NULL,
    DEPT_ID         NUMBER(10,0) NOT NULL,
    MUST_CHANGE_PWD VARCHAR2(1 CHAR),
    CONSTRAINT PK_EMP PRIMARY KEY (EMP_ID),
    CONSTRAINT FK_EMP_COM FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID),
    CONSTRAINT FK_EMP_POS FOREIGN KEY (POS_ID) REFERENCES EMP_POSITION (POS_ID),
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID)
);

-- 순환 참조 해결: DEPARTMENT → EMPLOYEE FK 추가
ALTER TABLE DEPARTMENT ADD CONSTRAINT FK5QMW9FWO73FYLB0328WIKA399
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID);

-- =============================================
-- 6. LEVEL 4 - EMPLOYEE 의존 테이블들
-- =============================================

CREATE TABLE EMP_AUTH (
    EMP_AUT_ID NUMBER NOT NULL,
    EMP_ID     NUMBER NOT NULL,
    AUT_ID     NUMBER NOT NULL,
    CONSTRAINT PK_EMP_AUTH PRIMARY KEY (EMP_AUT_ID),
    CONSTRAINT UQ_EMP_AUTH UNIQUE (EMP_ID, AUT_ID),
    CONSTRAINT FK_EMP_AUTH_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FK_EMP_AUTH_AUTH FOREIGN KEY (AUT_ID) REFERENCES AUTHORITY (AUT_ID)
);

CREATE TABLE ATTENDANCE (
    ATT_ID           NUMBER(19,0) NOT NULL,
    ATT_DATE         DATE NOT NULL,
    ATT_STATUS       VARCHAR2(20 CHAR),
    CHECK_IN         TIMESTAMP(9),
    CHECK_OUT        TIMESTAMP(9),
    CREATED_AT       TIMESTAMP(9),
    NIGHT_MINUTES    NUMBER(10,0),
    OVERTIME_MINUTES NUMBER(10,0),
    UPDATED_AT       TIMESTAMP(9),
    WORK_MINUTES     NUMBER(10,0),
    EMP_ID           NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_ATTENDANCE PRIMARY KEY (ATT_ID),
    CONSTRAINT UK_ATTENDANCE_DAILY UNIQUE (EMP_ID, ATT_DATE),
    CONSTRAINT FK59UGHL3N5VXS1XOP5EIURKC66 FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE SAL_STD (
    STD_ID     NUMBER NOT NULL,
    EMP_ID     NUMBER NOT NULL,
    BASE_SAL   NUMBER(15,0) NOT NULL,
    ANNU_SAL   NUMBER(15,0),
    START_DATE DATE NOT NULL,
    END_DATE   DATE,
    ACTV       NUMBER(1,0) DEFAULT 1 NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE NOT NULL,
    CONSTRAINT CK_SAL_STD_ACTV CHECK (ACTV IN (0, 1)),
    CONSTRAINT PK_SAL_STD PRIMARY KEY (STD_ID),
    CONSTRAINT FK_SAL_STD_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE SAL_ACCT (
    ACCT_ID    NUMBER NOT NULL,
    EMP_ID     NUMBER NOT NULL,
    BANK_NAME  VARCHAR2(50) NOT NULL,
    ACCT_NO    VARCHAR2(30) NOT NULL,
    HLDR_NAME  VARCHAR2(50) NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE NOT NULL,
    CONSTRAINT PK_SAL_ACCT PRIMARY KEY (ACCT_ID),
    CONSTRAINT UK_SAL_ACCT_EMP UNIQUE (EMP_ID),
    CONSTRAINT FK_SAL_ACCT_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE EMAIL_SEND_LOG (
    LOG_ID     NUMBER(10,0) NOT NULL,
    EMP_ID     NUMBER(10,0) NOT NULL,
    MAIL_TYPE  VARCHAR2(30) NOT NULL,
    STATUS     CHAR(1) DEFAULT 'P' NOT NULL,
    SENT_AT    DATE DEFAULT SYSDATE NOT NULL,
    ERROR_MSG  VARCHAR2(500),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_ESL_STATUS CHECK (STATUS IN ('P','S','F')),
    CONSTRAINT CK_ESL_MAIL_TYPE CHECK (MAIL_TYPE IN ('WELCOME','FOLLOWUP_3DAY')),
    CONSTRAINT PK_EMAIL_SEND_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT UK_ESL_EMP_TYPE UNIQUE (EMP_ID, MAIL_TYPE),
    CONSTRAINT FK_ESL_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE LEAVE_BALANCE (
    BALANCE_ID NUMBER(19,0) NOT NULL,
    CREATED_AT TIMESTAMP(9),
    TOTAL_DAYS NUMBER(5,2),
    UPDATED_AT TIMESTAMP(9),
    USED_DAYS  NUMBER(5,2),
    YEAR       NUMBER(10,0) NOT NULL,
    EMP_ID     NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_LEAVE_BALANCE PRIMARY KEY (BALANCE_ID),
    CONSTRAINT UK_LEAVE_BALANCE_YEAR UNIQUE (EMP_ID, YEAR),
    CONSTRAINT FKH7W554MA1IAQP6KIJ8CP923K FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE LEAVE_GRANT (
    GRANT_ID   NUMBER(19,0) NOT NULL,
    EXPIRE_AT  DATE,
    GRANT_DAYS NUMBER(5,2) NOT NULL,
    GRANT_TYPE VARCHAR2(20 CHAR) NOT NULL,
    GRANTED_AT TIMESTAMP(9),
    REASON     VARCHAR2(200 CHAR),
    EMP_ID     NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_LEAVE_GRANT PRIMARY KEY (GRANT_ID),
    CONSTRAINT FKLTJ81BC79NQH1OQ0L8VQLRULS FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE COM_RESOURCE (
    RES_ID         NUMBER NOT NULL,
    COM_ID         NUMBER NOT NULL,
    RES_CODE       VARCHAR2(50) NOT NULL,
    RES_NAME       VARCHAR2(100) NOT NULL,
    RES_TYPE       VARCHAR2(20) NOT NULL,
    QUANTITY       NUMBER NOT NULL,
    LOCATION       VARCHAR2(200),
    CAPACITY       NUMBER,
    RES_STATUS     VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    MANAGER_EMP_ID NUMBER,
    REMARK         VARCHAR2(255),
    CREATED_AT     DATE DEFAULT SYSDATE,
    UPDATED_AT     DATE DEFAULT SYSDATE,
    CONSTRAINT CK_COM_RESOURCE_TYPE CHECK (RES_TYPE IN ('ROOM','EQUIPMENT','VEHICLE')),
    CONSTRAINT CK_COM_RESOURCE_QTY CHECK (QUANTITY >= 0),
    CONSTRAINT CK_COM_RESOURCE_CAPACITY CHECK (CAPACITY IS NULL OR CAPACITY > 0),
    CONSTRAINT CK_COM_RESOURCE_STATUS CHECK (RES_STATUS IN ('AVAILABLE','MAINTENANCE','DISABLED')),
    CONSTRAINT PK_COM_RESOURCE PRIMARY KEY (RES_ID),
    CONSTRAINT UQ_COM_RESOURCE_COM_CODE UNIQUE (COM_ID, RES_CODE),
    CONSTRAINT FK_COM_RESOURCE_COMPANY1 FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID),
    CONSTRAINT FK_COM_RESOURCE_MANAGER1 FOREIGN KEY (MANAGER_EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE PROJECT (
    PRO_ID            NUMBER NOT NULL,
    EMP_ID            NUMBER NOT NULL,
    COM_ID            NUMBER NOT NULL,
    PRO_NAME          VARCHAR2(100) NOT NULL,
    PRO_DESC          VARCHAR2(1000),
    PRO_STATUS        VARCHAR2(20) DEFAULT 'TODO' NOT NULL,
    START_DATE        DATE NOT NULL,
    END_DATE          DATE NOT NULL,
    ACTUAL_START_DATE DATE,
    ACTUAL_END_DATE   DATE,
    CREATED_AT        DATE DEFAULT SYSDATE,
    UPDATED_AT        DATE DEFAULT SYSDATE,
    CONSTRAINT CK_PROJECT_STATUS CHECK (PRO_STATUS IN ('TODO','DOING','DONE')),
    CONSTRAINT CK_PROJECT_DATES CHECK (END_DATE >= START_DATE),
    CONSTRAINT PK_PROJECT PRIMARY KEY (PRO_ID),
    CONSTRAINT FK_PROJECT_EMPLOYEE1 FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FK_PROJECT_COMPANY1 FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID)
);

CREATE TABLE NOTICE (
    BNO        NUMBER NOT NULL,
    EMP_ID     NUMBER NOT NULL,
    COM_ID     NUMBER NOT NULL,
    BTITLE     VARCHAR2(200) NOT NULL,
    BCONTENT   CLOB,
    BHIT       NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
    BFILE      CLOB,
    CONSTRAINT PK_NOTICE PRIMARY KEY (BNO),
    CONSTRAINT FK_NOTICE_EMPLOYEE1 FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FK_NOTICE_COMPANY1 FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID)
);

CREATE TABLE DEPT_TRANSFER_LOG (
    LOG_ID            NUMBER NOT NULL,
    COM_ID            NUMBER NOT NULL,
    ORIGIN_DEPT_ID    NUMBER NOT NULL,
    TARGET_DEPT_ID    NUMBER NOT NULL,
    EMP_ID            NUMBER NOT NULL,
    AI_RECOMMENDED    VARCHAR2(1) DEFAULT 'N' NOT NULL,
    AI_REASON         VARCHAR2(1000),
    HANDOVER_SNAPSHOT CLOB,
    CREATED_BY        NUMBER NOT NULL,
    CREATED_AT        DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_DTL_AI_RECOMMENDED CHECK (AI_RECOMMENDED IN ('Y','N')),
    CONSTRAINT PK_DEPT_TRANSFER_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_DTL_COM FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID),
    CONSTRAINT FK_DTL_ORIGIN_DEPT FOREIGN KEY (ORIGIN_DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID),
    CONSTRAINT FK_DTL_TARGET_DEPT FOREIGN KEY (TARGET_DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID),
    CONSTRAINT FK_DTL_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FK_DTL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE HR_AI_CHAT_LOG (
    LOG_ID        NUMBER NOT NULL,
    EMP_ID        NUMBER NOT NULL,
    COM_ID        NUMBER NOT NULL,
    QUESTION      CLOB NOT NULL,
    ANSWER        CLOB NOT NULL,
    REF_CHUNK_IDS VARCHAR2(500),
    GROUNDED      NUMBER(1,0) NOT NULL,
    CREATED_AT    DATE NOT NULL,
    CONSTRAINT CK_HR_AI_CHAT_LOG_GRND CHECK (GROUNDED IN (0, 1)),
    CONSTRAINT PK_HR_AI_CHAT_LOG PRIMARY KEY (LOG_ID)
);

CREATE TABLE SAL_AI_CHAT_LOG (
    LOG_ID        NUMBER(19,0) NOT NULL,
    EMP_ID        NUMBER(19,0) NOT NULL,
    COM_ID        NUMBER(19,0) NOT NULL,
    QUESTION      CLOB,
    ANSWER        CLOB,
    REF_CHUNK_IDS VARCHAR2(500),
    GROUNDED      NUMBER(1,0) DEFAULT 0 NOT NULL,
    CREATED_AT    DATE NOT NULL,
    CONSTRAINT CK_SAL_AI_CHAT_LOG_GROUNDED CHECK (GROUNDED IN (0, 1)),
    CONSTRAINT PK_SAL_AI_CHAT_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_SAL_AI_CHAT_LOG_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE PERFORMANCE_EVALUATION (
    EVAL_ID              NUMBER NOT NULL,
    PERIOD_ID            NUMBER NOT NULL,
    TARGET_EMP_ID        NUMBER NOT NULL,
    EVALUATOR_ID         NUMBER NOT NULL,
    EVAL_TYPE            VARCHAR2(20) DEFAULT 'LEADER' NOT NULL,
    SCORE_PERFORMANCE    NUMBER(1,0),
    SCORE_EXPERTISE      NUMBER(1,0),
    SCORE_TEAMWORK       NUMBER(1,0),
    SCORE_ATTITUDE       NUMBER(1,0),
    SCORE_GROWTH         NUMBER(1,0),
    WEIGHTED_SCORE       NUMBER(5,2),
    STRENGTH_COMMENT     CLOB,
    IMPROVEMENT_COMMENT  CLOB,
    EVAL_STATUS          VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT           DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT           DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_EVAL_TYPE CHECK (EVAL_TYPE IN ('SELF','PEER','LEADER')),
    CONSTRAINT CK_EVAL_STATUS CHECK (EVAL_STATUS IN ('DRAFT','SUBMITTED')),
    CONSTRAINT CK_EVAL_SCORE_PERF CHECK (SCORE_PERFORMANCE IS NULL OR SCORE_PERFORMANCE BETWEEN 1 AND 5),
    CONSTRAINT CK_EVAL_SCORE_EXP CHECK (SCORE_EXPERTISE IS NULL OR SCORE_EXPERTISE BETWEEN 1 AND 5),
    CONSTRAINT CK_EVAL_SCORE_TEAM CHECK (SCORE_TEAMWORK IS NULL OR SCORE_TEAMWORK BETWEEN 1 AND 5),
    CONSTRAINT CK_EVAL_SCORE_ATT CHECK (SCORE_ATTITUDE IS NULL OR SCORE_ATTITUDE BETWEEN 1 AND 5),
    CONSTRAINT CK_EVAL_SCORE_GROW CHECK (SCORE_GROWTH IS NULL OR SCORE_GROWTH BETWEEN 1 AND 5),
    CONSTRAINT CK_EVAL_WEIGHTED CHECK (WEIGHTED_SCORE IS NULL OR WEIGHTED_SCORE BETWEEN 1 AND 5),
    CONSTRAINT CK_EVAL_SELF_MATCH CHECK (
        (EVAL_TYPE = 'SELF' AND TARGET_EMP_ID = EVALUATOR_ID) OR
        (EVAL_TYPE IN ('LEADER','PEER') AND TARGET_EMP_ID <> EVALUATOR_ID)
    ),
    CONSTRAINT PK_EVAL PRIMARY KEY (EVAL_ID),
    CONSTRAINT UQ_EVAL UNIQUE (PERIOD_ID, TARGET_EMP_ID, EVALUATOR_ID, EVAL_TYPE),
    CONSTRAINT FK_EVAL_PERIOD FOREIGN KEY (PERIOD_ID) REFERENCES EVALUATION_PERIOD (PERIOD_ID),
    CONSTRAINT FK_EVAL_TARGET FOREIGN KEY (TARGET_EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FK_EVAL_EVALUATOR FOREIGN KEY (EVALUATOR_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE EVALUATION_AI_REPORT (
    REPORT_ID            NUMBER NOT NULL,
    PERIOD_ID            NUMBER NOT NULL,
    EMP_ID               NUMBER NOT NULL,
    AVG_PERFORMANCE      NUMBER(5,2),
    AVG_EXPERTISE        NUMBER(5,2),
    AVG_TEAMWORK         NUMBER(5,2),
    AVG_ATTITUDE         NUMBER(5,2),
    AVG_GROWTH           NUMBER(5,2),
    OVERALL_SCORE        NUMBER(5,2),
    GRADE                VARCHAR2(2 CHAR),
    AI_SUMMARY           CLOB,
    SENTIMENT_POSITIVE   NUMBER(5,2),
    SENTIMENT_NEUTRAL    NUMBER(5,2),
    SENTIMENT_NEGATIVE   NUMBER(5,2),
    SENTIMENT_LABEL      VARCHAR2(20),
    MODEL_NAME           VARCHAR2(50),
    GENERATED_AT         DATE DEFAULT SYSDATE,
    CREATED_AT           DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT           DATE DEFAULT SYSDATE NOT NULL,
    ATT_WORK_DAYS        NUMBER(5,0) DEFAULT 0,
    ATT_LATE_COUNT       NUMBER(5,0) DEFAULT 0,
    ATT_EARLY_LEAVE_COUNT NUMBER(5,0) DEFAULT 0,
    ATT_ABSENT_COUNT     NUMBER(5,0) DEFAULT 0,
    ATT_ANNUAL_USED      NUMBER(5,1) DEFAULT 0,
    ATT_TOTAL_WORK_MIN   NUMBER(10,0) DEFAULT 0,
    ATT_OVERTIME_MIN     NUMBER(10,0) DEFAULT 0,
    ATT_RATE             NUMBER(5,2) DEFAULT 0,
    CONSTRAINT CK_REPORT_AVG_PERF CHECK (AVG_PERFORMANCE IS NULL OR AVG_PERFORMANCE BETWEEN 1 AND 5),
    CONSTRAINT CK_REPORT_AVG_EXP CHECK (AVG_EXPERTISE IS NULL OR AVG_EXPERTISE BETWEEN 1 AND 5),
    CONSTRAINT CK_REPORT_AVG_TEAM CHECK (AVG_TEAMWORK IS NULL OR AVG_TEAMWORK BETWEEN 1 AND 5),
    CONSTRAINT CK_REPORT_AVG_ATT CHECK (AVG_ATTITUDE IS NULL OR AVG_ATTITUDE BETWEEN 1 AND 5),
    CONSTRAINT CK_REPORT_AVG_GROW CHECK (AVG_GROWTH IS NULL OR AVG_GROWTH BETWEEN 1 AND 5),
    CONSTRAINT CK_REPORT_OVERALL CHECK (OVERALL_SCORE IS NULL OR OVERALL_SCORE BETWEEN 0 AND 5),
    CONSTRAINT CK_REPORT_GRADE CHECK (GRADE IS NULL OR GRADE IN ('S','A','B','C','D')),
    CONSTRAINT CK_REPORT_SENT_POS CHECK (SENTIMENT_POSITIVE IS NULL OR SENTIMENT_POSITIVE BETWEEN 0 AND 100),
    CONSTRAINT CK_REPORT_SENT_NEU CHECK (SENTIMENT_NEUTRAL IS NULL OR SENTIMENT_NEUTRAL BETWEEN 0 AND 100),
    CONSTRAINT CK_REPORT_SENT_NEG CHECK (SENTIMENT_NEGATIVE IS NULL OR SENTIMENT_NEGATIVE BETWEEN 0 AND 100),
    CONSTRAINT CK_REPORT_SENT_SUM CHECK (
        (SENTIMENT_POSITIVE IS NULL AND SENTIMENT_NEUTRAL IS NULL AND SENTIMENT_NEGATIVE IS NULL) OR
        (ABS((SENTIMENT_POSITIVE + SENTIMENT_NEUTRAL + SENTIMENT_NEGATIVE) - 100) < 0.01)
    ),
    CONSTRAINT CK_REPORT_SENT_LABEL CHECK (SENTIMENT_LABEL IS NULL OR SENTIMENT_LABEL IN ('POSITIVE','NEUTRAL','NEGATIVE')),
    CONSTRAINT PK_REPORT PRIMARY KEY (REPORT_ID),
    CONSTRAINT UQ_REPORT UNIQUE (PERIOD_ID, EMP_ID),
    CONSTRAINT FK_REPORT_PERIOD FOREIGN KEY (PERIOD_ID) REFERENCES EVALUATION_PERIOD (PERIOD_ID),
    CONSTRAINT FK_REPORT_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

-- =============================================
-- 7. LEVEL 5
-- =============================================

CREATE TABLE PROJECT_MEMBER (
    PM_ID           NUMBER NOT NULL,
    PROJECT_PRO_ID  NUMBER NOT NULL,
    EMP_ID          NUMBER NOT NULL,
    MEMBER_ROLE     VARCHAR2(50) NOT NULL,
    JOINED_AT       DATE NOT NULL,
    CONSTRAINT PK_PROJECT_MEMBER PRIMARY KEY (PM_ID),
    CONSTRAINT UQ_PROJECT_MEMBER UNIQUE (PROJECT_PRO_ID, EMP_ID),
    CONSTRAINT FK_PROJECT_MEMBER_PROJECT1 FOREIGN KEY (PROJECT_PRO_ID) REFERENCES PROJECT (PRO_ID),
    CONSTRAINT FK_PROJECT_MEMBER_EMPLOYEE1 FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE SAL_PAY (
    PAY_ID      NUMBER NOT NULL,
    EMP_ID      NUMBER NOT NULL,
    STD_ID      NUMBER,
    PAY_MONTH   DATE NOT NULL,
    BASE_SAL    NUMBER(15,0) NOT NULL,
    ALLOW_TOTAL NUMBER(15,0) NOT NULL,
    DEDT_TOTAL  NUMBER(15,0) NOT NULL,
    NET_PAY     NUMBER(15,0) NOT NULL,
    STAT        VARCHAR2(20) NOT NULL,
    REJ_RSN     VARCHAR2(500),
    PAID_AT     DATE,
    BANK_NAME   VARCHAR2(50),
    ACCT_NO     VARCHAR2(30),
    HLDR_NAME   VARCHAR2(50),
    CREATED_AT  DATE NOT NULL,
    UPDATED_AT  DATE NOT NULL,
    CONSTRAINT CK_SAL_PAY_STAT CHECK (STAT IN ('PENDING','APPROVED','PAID','REJECTED')),
    CONSTRAINT PK_SAL_PAY PRIMARY KEY (PAY_ID),
    CONSTRAINT FK_SAL_PAY_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FK_SAL_PAY_STD FOREIGN KEY (STD_ID) REFERENCES SAL_STD (STD_ID)
);

CREATE TABLE RECRUIT (
    REC_ID             NUMBER(19,0) NOT NULL,
    CREATED_AT         TIMESTAMP(9),
    REC_DEPARTMENT     VARCHAR2(100 CHAR),
    REC_DESCRIPTION    CLOB,
    REC_EMPLOYMENT_TYPE VARCHAR2(50 CHAR),
    REC_END_DATE       TIMESTAMP(9),
    REC_HEADCOUNT      NUMBER(19,0),
    REC_POSITION       VARCHAR2(100 CHAR),
    REC_START_DATE     TIMESTAMP(9),
    REC_STATUS         VARCHAR2(20 CHAR) NOT NULL,
    REC_TITLE          VARCHAR2(200 CHAR) NOT NULL,
    UPDATED_AT         TIMESTAMP(9),
    COM_ID             NUMBER(19,0) NOT NULL,
    EMP_ID             NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_RECRUIT PRIMARY KEY (REC_ID),
    CONSTRAINT FKNO0U44S7A75FOADH1BFXR5X83 FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID),
    CONSTRAINT FKFYBX9CRF30OM0NLTS7TTSB2OT FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE RESERVATION (
    REV_ID          NUMBER NOT NULL,
    RES_ID          NUMBER NOT NULL,
    COM_ID          NUMBER NOT NULL,
    EMP_ID          NUMBER NOT NULL,
    QUANTITY        NUMBER NOT NULL,
    STATUS          VARCHAR2(10) DEFAULT 'WAI' NOT NULL,
    START_DT        TIMESTAMP(6) NOT NULL,
    END_DT          TIMESTAMP(6) NOT NULL,
    RETURN_DT       TIMESTAMP(6),
    APPROVED_EMP_ID NUMBER,
    APPROVED_AT     DATE,
    REJECT_REASON   VARCHAR2(500),
    REMARK          VARCHAR2(255),
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE DEFAULT SYSDATE,
    NOSHOW_ALERT_AT TIMESTAMP(9),
    RISK_SCORE      BINARY_DOUBLE,
    CONSTRAINT CK_RESERVATION_STATUS CHECK (STATUS IN ('WAI','APP','REJ','NORET')),
    CONSTRAINT CK_RESERVATION_QTY CHECK (QUANTITY > 0),
    CONSTRAINT CK_RESERVATION_DATES CHECK (END_DT >= START_DT),
    CONSTRAINT PK_RESERVATION PRIMARY KEY (REV_ID),
    CONSTRAINT FK_RESERVATION_EMPLOYEE1 FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FK_RESERVATION_APPROVER1 FOREIGN KEY (APPROVED_EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FK_RESERVATION_COMPANY1 FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID),
    CONSTRAINT FK_RESERVATION_COM_RESOURCE1 FOREIGN KEY (RES_ID) REFERENCES COM_RESOURCE (RES_ID)
);

CREATE TABLE APPR_DOC (
    DOC_ID       NUMBER NOT NULL,
    EMP_ID       NUMBER NOT NULL,
    FOR_ID       NUMBER NOT NULL,
    COM_ID       NUMBER NOT NULL,
    DOC_TITLE    VARCHAR2(100) NOT NULL,
    DOC_CONTENT  CLOB,
    DOC_STATUS   VARCHAR2(20) DEFAULT 'ING' NOT NULL,
    CREATED_AT   DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT   DATE DEFAULT SYSDATE NOT NULL,
    IS_IMPORTANT NUMBER(1,0) DEFAULT 0 NOT NULL,
    DOC_REVISION NUMBER DEFAULT 1 NOT NULL,
    FOR_VERSION  NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT CK_APPR_DOC_IMPORTANT CHECK (IS_IMPORTANT IN (0,1)),
    CONSTRAINT CK_APPR_DOC_STATUS CHECK (DOC_STATUS IN ('ING','APP','REJ','CAN')),
    CONSTRAINT PK_APPR_DOC PRIMARY KEY (DOC_ID),
    CONSTRAINT FK_APPR_DOC_APPR_FORM1 FOREIGN KEY (FOR_ID, FOR_VERSION) REFERENCES APPR_FORM (FOR_ID, FOR_VERSION),
    CONSTRAINT FK_APPR_DOC_COMPANY1 FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID),
    CONSTRAINT FK_APPR_DOC_EMPLOYEE1 FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

-- =============================================
-- 8. LEVEL 6
-- =============================================

CREATE TABLE TASK (
    TASK_ID         NUMBER NOT NULL,
    PRO_ID          NUMBER NOT NULL,
    PM_ID           NUMBER NOT NULL,
    COM_ID          NUMBER NOT NULL,
    PARENT_TASK_ID  NUMBER,
    TASK_NAME       VARCHAR2(100) NOT NULL,
    TASK_DESC       VARCHAR2(1000) NOT NULL,
    TASK_STATUS     VARCHAR2(20) DEFAULT 'TODO' NOT NULL,
    TASK_START_DATE DATE NOT NULL,
    TASK_END_DATE   DATE NOT NULL,
    ACTUAL_START_DATE DATE,
    ACTUAL_END_DATE   DATE,
    CREATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_TASK_STATUS CHECK (TASK_STATUS IN ('TODO','DOING','DONE')),
    CONSTRAINT CK_TASK_DATES CHECK (TASK_END_DATE >= TASK_START_DATE),
    CONSTRAINT CK_TASK_NOT_SELF_PARENT CHECK (PARENT_TASK_ID != TASK_ID),
    CONSTRAINT PK_TASK PRIMARY KEY (TASK_ID),
    CONSTRAINT FK_TASK_PROJECT1 FOREIGN KEY (PRO_ID) REFERENCES PROJECT (PRO_ID),
    CONSTRAINT FK_TASK_COMPANY1 FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID),
    CONSTRAINT FK_TASK_PROJECT_MEMBER FOREIGN KEY (PM_ID) REFERENCES PROJECT_MEMBER (PM_ID),
    CONSTRAINT FK_TASK_PARENT FOREIGN KEY (PARENT_TASK_ID) REFERENCES TASK (TASK_ID) ON DELETE SET NULL
);

CREATE TABLE SAL_PAY_ITEM (
    ITEM_ID   NUMBER NOT NULL,
    PAY_ID    NUMBER NOT NULL,
    ITEM_CODE VARCHAR2(30) NOT NULL,
    AMT       NUMBER(15,0) NOT NULL,
    CONSTRAINT PK_SAL_PAY_ITEM PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_SAL_PAY_ITEM_PAY FOREIGN KEY (PAY_ID) REFERENCES SAL_PAY (PAY_ID) ON DELETE CASCADE
);

CREATE TABLE APPLICANT (
    APCT_ID          NUMBER(19,0) NOT NULL,
    APCT_DATE        TIMESTAMP(9),
    APCT_EMAIL       VARCHAR2(100 CHAR),
    APCT_NAME        VARCHAR2(50 CHAR) NOT NULL,
    APCT_PHONE       VARCHAR2(20 CHAR) NOT NULL,
    APCT_STATUS      VARCHAR2(20 CHAR) NOT NULL,
    CREATED_AT       TIMESTAMP(9),
    APCT_PROVIDER    VARCHAR2(255 CHAR),
    APCT_PROVIDER_ID VARCHAR2(255 CHAR),
    UPDATED_AT       TIMESTAMP(9),
    COM_ID           NUMBER(19,0) NOT NULL,
    REC_ID           NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_APPLICANT PRIMARY KEY (APCT_ID),
    CONSTRAINT UQ_APPLICANT_PROVIDER UNIQUE (REC_ID, APCT_PROVIDER, APCT_PROVIDER_ID),
    CONSTRAINT FKPSO9VX8FXNNLKCUSY6EGLSB70 FOREIGN KEY (COM_ID) REFERENCES COMPANY (COM_ID),
    CONSTRAINT FKPAV1CQ6GDKY9C1005QKSUGXA0 FOREIGN KEY (REC_ID) REFERENCES RECRUIT (REC_ID)
);

CREATE TABLE APPR_LINE (
    LIN_ID       NUMBER NOT NULL,
    DOC_ID       NUMBER NOT NULL,
    EMP_ID       NUMBER NOT NULL,
    LIN_ORDER    NUMBER NOT NULL,
    LIN_STATUS   VARCHAR2(20) NOT NULL,
    LIN_APPROVED DATE,
    CONSTRAINT CK_APPR_LINE_STATUS CHECK (LIN_STATUS IN ('NOT','WAI','APP','REJ')),
    CONSTRAINT PK_APPR_LINE PRIMARY KEY (LIN_ID),
    CONSTRAINT UQ_APPR_LINE_DOC_ORDER UNIQUE (DOC_ID, LIN_ORDER),
    CONSTRAINT FK_APPR_LINE_APPR_DOC1 FOREIGN KEY (DOC_ID) REFERENCES APPR_DOC (DOC_ID),
    CONSTRAINT FK_APPR_LINE_EMPLOYEE1 FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE APPR_FILE (
    FILE_ID      NUMBER(19,0) NOT NULL,
    CONTENT_TYPE VARCHAR2(100 CHAR),
    CREATED_AT   TIMESTAMP(9) NOT NULL,
    FILE_SIZE    NUMBER(19,0) NOT NULL,
    FILE_URL     VARCHAR2(500 CHAR) NOT NULL,
    ORIG_NAME    VARCHAR2(255 CHAR) NOT NULL,
    SAVED_NAME   VARCHAR2(255 CHAR) NOT NULL,
    SAVED_PATH   VARCHAR2(500 CHAR) NOT NULL,
    DOC_ID       NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_APPR_FILE PRIMARY KEY (FILE_ID),
    CONSTRAINT FKRCAQVLMSU0GGJE14CMFJB1T7L FOREIGN KEY (DOC_ID) REFERENCES APPR_DOC (DOC_ID)
);

CREATE TABLE APPR_FORM_DELEGATION_CONFIG (
    CFG_ID             NUMBER(19,0) NOT NULL,
    CREATED_AT         TIMESTAMP(9) NOT NULL,
    DELEGATE_FIELD_ID  VARCHAR2(20 CHAR) NOT NULL,
    ENABLED            NUMBER(1,0) NOT NULL,
    END_FIELD_ID       VARCHAR2(20 CHAR) NOT NULL,
    MIN_TRIGGER_DAYS   NUMBER(10,0) NOT NULL,
    START_FIELD_ID     VARCHAR2(20 CHAR) NOT NULL,
    UPDATED_AT         TIMESTAMP(9) NOT NULL,
    FOR_ID             NUMBER(19,0),
    FOR_VERSION        NUMBER(19,0),
    CHECK (ENABLED IN (0,1)),
    CONSTRAINT PK_APPR_FORM_DELEG_CFG PRIMARY KEY (CFG_ID),
    CONSTRAINT UQ_FORM_DELEG_CFG UNIQUE (FOR_ID, FOR_VERSION),
    CONSTRAINT FK74L0T776NTP8EJBJA3YHLPIBO FOREIGN KEY (FOR_ID, FOR_VERSION) REFERENCES APPR_FORM (FOR_ID, FOR_VERSION)
);

CREATE TABLE LEAVE_REQUEST (
    REQ_ID     NUMBER(19,0) NOT NULL,
    END_DATE   DATE NOT NULL,
    REQ_DAYS   BINARY_DOUBLE NOT NULL,
    REQ_STATUS VARCHAR2(20 CHAR) NOT NULL,
    START_DATE DATE NOT NULL,
    DOC_ID     NUMBER(19,0) NOT NULL,
    EMP_ID     NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_LEAVE_REQUEST PRIMARY KEY (REQ_ID),
    CONSTRAINT UKORQ8YULO50ODBEY9AHS56ME2D UNIQUE (DOC_ID),
    CONSTRAINT FKK3IWW85S6GVHD0KXFD2HLSBOU FOREIGN KEY (DOC_ID) REFERENCES APPR_DOC (DOC_ID),
    CONSTRAINT FKOMS91MEHFEIR8XI99K2BWMQES FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE APPR_LINE_FAVORITE (
    FAV_ID    NUMBER(19,0) NOT NULL,
    EMP_IDS   VARCHAR2(4000 CHAR) NOT NULL,
    FOR_ID    NUMBER(19,0) NOT NULL,
    USE_COUNT NUMBER(10,0) NOT NULL,
    DEPT_ID   NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_APPR_LINE_FAV PRIMARY KEY (FAV_ID),
    CONSTRAINT FKRUYF80OLHHOKG4PFJ0OGDA924 FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID)
);

-- =============================================
-- 9. LEVEL 7
-- =============================================

CREATE TABLE APPR_AUTO_DELEGATION (
    AUTO_DELEG_ID NUMBER(19,0) NOT NULL,
    CANC_REASON   VARCHAR2(500 CHAR),
    CREATED_AT    TIMESTAMP(9) NOT NULL,
    DELEG_STATUS  VARCHAR2(20 CHAR) NOT NULL,
    END_DATE      DATE NOT NULL,
    PROCESSED_AT  TIMESTAMP(9),
    START_DATE    DATE NOT NULL,
    DOC_ID        NUMBER(19,0) NOT NULL,
    DEL_EMP_ID    NUMBER(19,0) NOT NULL,
    NEW_EMP_ID    NUMBER(19,0) NOT NULL,
    PROC_EMP_ID   NUMBER(19,0),
    CONSTRAINT PK_APPR_AUTO_DELEG PRIMARY KEY (AUTO_DELEG_ID),
    CONSTRAINT FKLXETRQ5MYJCG5CSUHXQNU8IY5 FOREIGN KEY (DOC_ID) REFERENCES APPR_DOC (DOC_ID),
    CONSTRAINT FKHU0BV9WDV32EE903UE2XIT0OJ FOREIGN KEY (DEL_EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FKE2P106O8SB666FU20TLSPT81A FOREIGN KEY (NEW_EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FKN8AQMRFMSB5106IXAKG9O8IB1 FOREIGN KEY (PROC_EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE APPR_LINE_REQUEST (
    REQ_ID       NUMBER(19,0) NOT NULL,
    CREATED_AT   TIMESTAMP(9) NOT NULL,
    PROCESSED_AT TIMESTAMP(9),
    REQ_REASON   VARCHAR2(500 CHAR),
    REQ_STATUS   VARCHAR2(10 CHAR) NOT NULL,
    DOC_ID       NUMBER(19,0) NOT NULL,
    LIN_ID       NUMBER(19,0) NOT NULL,
    NEW_EMP_ID   NUMBER(19,0),
    ORI_EMP_ID   NUMBER(19,0) NOT NULL,
    PRO_EMP_ID   NUMBER(19,0),
    REQ_EMP_ID   NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_APPR_LINE_REQ PRIMARY KEY (REQ_ID),
    CONSTRAINT FKEQA13CS9988AKFC346OXARNEX FOREIGN KEY (DOC_ID) REFERENCES APPR_DOC (DOC_ID),
    CONSTRAINT FKC7FCPO5M0DO9V1BR8NYC60LOT FOREIGN KEY (LIN_ID) REFERENCES APPR_LINE (LIN_ID),
    CONSTRAINT FKPAPMJSSKHPAKDRIAGWNYVCIYN FOREIGN KEY (NEW_EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FKH5LBN7K4KW0XCRCHDW8WWLO80 FOREIGN KEY (ORI_EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FKDEAI93CB0Q989DI3LKMNREJCW FOREIGN KEY (PRO_EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FK2TRVBYGIRIV9V3V93KNSMWDS1 FOREIGN KEY (REQ_EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE APPR_LOG (
    LOG_ID        NUMBER(19,0) NOT NULL,
    CREATED_AT    TIMESTAMP(9) NOT NULL,
    ACT_EMP_ID    NUMBER(19,0) NOT NULL,
    DOC_ID        NUMBER(19,0) NOT NULL,
    ORI_EMP_ID    NUMBER(19,0) NOT NULL,
    PER_EMP_ID    NUMBER(19,0) NOT NULL,
    AUTO_DELEG_ID NUMBER(19,0),
    CONSTRAINT PK_APPR_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT FKIUL8BYWXC5DPHCKBGC0QO5UKQ FOREIGN KEY (AUTO_DELEG_ID) REFERENCES APPR_AUTO_DELEGATION (AUTO_DELEG_ID),
    CONSTRAINT FK7ET1B4N7U51FWYNURQU6D9TNR FOREIGN KEY (ACT_EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FKCQG3H7YIDLJKL8KN38E84LNAO FOREIGN KEY (DOC_ID) REFERENCES APPR_DOC (DOC_ID),
    CONSTRAINT FK5HL2NDD2NI8KJ4JLUQSRM4BGQ FOREIGN KEY (ORI_EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    CONSTRAINT FKN4S8KG7XGIKGFP8MEP10FQ9AF FOREIGN KEY (PER_EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

CREATE TABLE RESUME (
    RSM_ID           NUMBER(19,0) NOT NULL,
    RSM_AI_SUMMARY   CLOB,
    RSM_ANALYZED_AT  TIMESTAMP(9),
    RSM_EXTRACTED_TEXT CLOB,
    RSM_FILE_NAME    VARCHAR2(200 CHAR),
    RSM_FILE_URL     VARCHAR2(500 CHAR),
    RSM_FIT_SCORE    NUMBER(19,0),
    RSM_STATUS       VARCHAR2(20 CHAR) NOT NULL,
    RSM_UPLOADED_AT  TIMESTAMP(9),
    APCT_ID          NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_RESUME PRIMARY KEY (RSM_ID),
    CONSTRAINT FKOHEX372E1IWPOCBNPWNFXPVPB FOREIGN KEY (APCT_ID) REFERENCES APPLICANT (APCT_ID)
);

CREATE TABLE RESUME_CHUNK (
    CHUNK_ID        NUMBER(19,0) NOT NULL,
    CHUNK_EMBEDDING CLOB NOT NULL,
    CHUNK_ORDER     NUMBER(19,0) NOT NULL,
    CHUNK_TEXT      CLOB NOT NULL,
    RSM_ID          NUMBER(19,0) NOT NULL,
    CONSTRAINT UK_RESUME_CHUNK_ORDER UNIQUE (RSM_ID, CHUNK_ORDER),
    CONSTRAINT PK_RESUME_CHUNK PRIMARY KEY (CHUNK_ID),
    CONSTRAINT FKFHC77X5TIF4X82LF70EMLYCJD FOREIGN KEY (RSM_ID) REFERENCES RESUME (RSM_ID)
);

-- =============================================
-- 10. GLOBAL TEMPORARY TABLES
-- =============================================

CREATE GLOBAL TEMPORARY TABLE HTE_APPR_AUTO_DELEGATION (
    ENDDATE          DATE,
    RN_              NUMBER(10,0) NOT NULL,
    STARTDATE        DATE,
    APPRDOC_DOCID    NUMBER(19,0),
    AUTODELEGID      NUMBER(19,0),
    DELEMP_EMPID     NUMBER(19,0),
    NEWEMP_EMPID     NUMBER(19,0),
    PROCEMP_EMPID    NUMBER(19,0),
    PROCESSEDAT      TIMESTAMP(9),
    DELEGSTATUS      VARCHAR2(20 CHAR),
    CANCREASON       VARCHAR2(500 CHAR),
    PRIMARY KEY (RN_)
) ON COMMIT DELETE ROWS;

CREATE GLOBAL TEMPORARY TABLE HTE_APPR_FORM_DELEGATION_CONFIG (
    ENABLED          NUMBER(1,0),
    MINTRIGGERDAYS   NUMBER(10,0),
    RN_              NUMBER(10,0) NOT NULL,
    CFGID            NUMBER(19,0),
    FORID            NUMBER(19,0),
    FORVERSION       NUMBER(19,0),
    DELEGATEFIELDID  VARCHAR2(20 CHAR),
    ENDFIELDID       VARCHAR2(20 CHAR),
    STARTFIELDID     VARCHAR2(20 CHAR),
    PRIMARY KEY (RN_)
) ON COMMIT DELETE ROWS;

-- =============================================
-- 완료
-- =============================================
COMMIT;